# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "PostgreSQL-GeoPackage-vagrant"
  config.vm.synced_folder  "..", "/home/vagrant/PostgreSQL-GeoPackage"

  # Fixing "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device" messages
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  config.vm.provision "shell", path: "scripts/repositories.sh"
  config.vm.provision "shell", path: "scripts/packages.sh"
  config.vm.provision "shell", path: "scripts/user_custom.sh"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  config.cache.synced_folder_opts = {
    owner: "_apt",
  }

  config.vm.provider "virtualbox" do |v|
    v.name = "PostgreSQL-GeoPackage-vagrant"
    v.customize ["modifyvm", :id, "--memory", 1024, "--cpus", 2]
    v.customize ["modifyvm", :id, "--ioapic", "on", "--largepages", "off", "--vtxvpid", "off"]
  end
end
